// Vercel serverless function: /api/chat
// Empathetic mental wellness companion for Indian competitive exam students.
// Proxies chat requests to Google Gemini using native fetch — no SDK.

const GEMINI_MODEL = 'gemini-2.0-flash';
const GEMINI_ENDPOINT = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`;

// Turns the last-7-days history into a short, readable summary for the prompt.
function summarizeHistory(history) {
  if (!Array.isArray(history) || history.length === 0) {
    return 'No mood history is available for the past week.';
  }

  const lines = history.map((entry) => {
    const date = entry?.date ? String(entry.date) : 'unknown date';
    const mood =
      typeof entry?.mood === 'number' ? `${entry.mood}/10` : 'no mood score';
    const journal = entry?.journal
      ? ` — note: "${String(entry.journal).slice(0, 120)}"`
      : '';
    return `- ${date}: mood ${mood}${journal}`;
  });

  const scores = history
    .map((e) => e?.mood)
    .filter((m) => typeof m === 'number');
  const average =
    scores.length > 0
      ? (scores.reduce((sum, m) => sum + m, 0) / scores.length).toFixed(1)
      : 'N/A';

  return `Average mood over the period: ${average}/10.\n${lines.join('\n')}`;
}

function buildSystemPrompt({ examType, mood, journal, history }) {
  const examLabel = examType || 'a competitive exam';
  const moodLabel = typeof mood === 'number' ? `${mood}/10` : 'not provided';
  const historySummary = summarizeHistory(history);
  const journalText = journal
    ? `Today's journal entry: "${journal}"`
    : 'No journal entry was provided today.';

  return [
    'You are an empathetic mental wellness companion for Indian students preparing for competitive exams.',
    `The student is preparing for ${examLabel}. Their current mood score is ${moodLabel}.`,
    '',
    'Last 7 days mood history:',
    historySummary,
    '',
    journalText,
    '',
    'Your responsibilities:',
    "- Carefully read the journal entry and mood history to detect specific stress triggers (e.g., comparison with peers, syllabus pressure, family expectations, sleep, self-doubt).",
    '- Offer hyper-personalized coping strategies, mindfulness tips, or motivation tailored to this student and their exam.',
    '- Acknowledge the cultural context of Indian competitive exams without being preachy.',
    '',
    'Style rules:',
    '- Keep every response under 150 words.',
    '- Be warm, encouraging, and human — never clinical or robotic.',
    '- Do not diagnose. If the student appears to be in crisis, gently suggest reaching out to a trusted person or a helpline.',
  ].join('\n');
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST');
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return res.status(500).json({ error: 'GEMINI_API_KEY is not configured' });
  }

  let body;
  try {
    body =
      typeof req.body === 'string' ? JSON.parse(req.body) : req.body || {};
  } catch (err) {
    return res.status(400).json({ error: 'Invalid JSON body' });
  }

  const { examType, mood, journal, history, message } = body;

  if (!message || typeof message !== 'string' || !message.trim()) {
    return res.status(400).json({ error: 'A non-empty "message" is required' });
  }

  try {
    const systemPrompt = buildSystemPrompt({ examType, mood, journal, history });

    const payload = {
      systemInstruction: { parts: [{ text: systemPrompt }] },
      contents: [{ role: 'user', parts: [{ text: message }] }],
      generationConfig: {
        temperature: 0.8,
        maxOutputTokens: 300,
      },
    };

    const response = await fetch(`${GEMINI_ENDPOINT}?key=${apiKey}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const detail = await response.text();
      return res
        .status(response.status === 429 ? 429 : 502)
        .json({ error: 'Gemini API error', detail });
    }

    const data = await response.json();
    const reply = data?.candidates?.[0]?.content?.parts?.[0]?.text?.trim();

    if (!reply) {
      return res
        .status(502)
        .json({ error: 'No reply generated by the model' });
    }

    return res.status(200).json({ reply });
  } catch (err) {
    return res
      .status(500)
      .json({ error: 'Internal server error', detail: String(err) });
  }
}
